version: '3.4'

networks:
  udemy-network:
    driver: bridge
volumes:
  db-data:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest    
    environment:
      - SA_PASSWORD:"Your_password123"
      - ACCEPT_EULA:"Y"
      - DATABASE:"rest_aspnet_udemy"
    volumes:
      - db-data:./DBBackup/backup.sql      
    ports:
     - "3306:3306"
    networks:
      - udemy-network

  sandboxrestapiudemy:
    image: sandboxrestapiudemy-API
    build:
      context: .
      dockerfile: SandBoxRestApiUdemy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"   
    networks:
       - udemy-network   